// Copyright 2022 Kosterin Alexey
#ifndef MODULES_TASK_2_KOSTERIN_A_GAUS_LENT_HORIZ_GAUS_LENT_HORIZ_H_
#define MODULES_TASK_2_KOSTERIN_A_GAUS_LENT_HORIZ_GAUS_LENT_HORIZ_H_

double Gaus(double **a, double *b, int size);

#endif  // MODULES_TASK_2_KOSTERIN_A_GAUS_LENT_HORIZ_GAUS_LENT_HORIZ_H_
