// Copyright 2021 Musin Alexandr
#ifndef MODULES_TASK_2_MUSIN_A_DINING_PHILOSOPHERS_DINING_PHILOSOPHERS_H_
#define MODULES_TASK_2_MUSIN_A_DINING_PHILOSOPHERS_DINING_PHILOSOPHERS_H_
int manager(int size);
void philosoph(int rank, int param);
#endif  // MODULES_TASK_2_MUSIN_A_DINING_PHILOSOPHERS_DINING_PHILOSOPHERS_H_
