// Copyright 2022 Semenova Veronika
#ifndef MODULES_TASK_1_SEMENOVA_A_VECTOR_ALTERNATING_SIGNS_VECTOR_ALTERNATING_SIGNS_H_
#define MODULES_TASK_1_SEMENOVA_A_VECTOR_ALTERNATING_SIGNS_VECTOR_ALTERNATING_SIGNS_H_

void RandVec(int* V, int n);

int SerialSum(const int* V, int n);

int ParallelSum(const int* V, int n);

#endif  // MODULES_TASK_1_SEMENOVA_A_VECTOR_ALTERNATING_SIGNS_VECTOR_ALTERNATING_SIGNS_H_