// Copyright 2022 Zagrebin S.

#ifndef MODULES_TASK_1_ZAGREBIN_S_SENTENCE_COUNT_SENTENCE_COUNT_H_
#define MODULES_TASK_1_ZAGREBIN_S_SENTENCE_COUNT_SENTENCE_COUNT_H_

void countSentences(int *res, const char *str);

#endif  // MODULES_TASK_1_ZAGREBIN_S_SENTENCE_COUNT_SENTENCE_COUNT_H_
